### PR TITLE
Clocksource select

### PR DESCRIPTION
**Pull request by HEnquist**
Next step of the pitch adjust.
This PR adds a clock source selector, with two options.
Selecting "Internal Fixed" disables pitch adjust and fixes the pitch at 100%), while "Internal Adjustable" enables it.

### CODE REVIEW

**Comment by HEnquist** [comment]
I have not done anything to the documentation yet. That should definitely be done as well.

**Comment by devinroth** [comment]
I was thinking, do you think it would be possible to hide the balance slider when set to "Internal Fixed?" I just anticipate people not understanding what's going on. I've had people complain when I disabled a volume control that did absolutely nothing. I don't know if controls can be dynamic but I don't see why not.

**Comment by HEnquist** [comment]
Yeah hiding the pan control would be quite helpful. I will try to see if I can get it to work.

**Comment by HEnquist** [comment]
I'm trying to dynamically hide or disable the pan control, but I'm not very successful. I first tried modifying the `BlackHole_HasControlProperty` function, but that did nothing. Then I tried making the control not writable, but that didn't go any better.
Now I'm trying the `BlackHole_GetDevicePropertyData` function, to only include the pan control when pitch adjust is enabled. This at least responds to what I am doing. But I can't get it to change dynamically, only the default value at startup determines if pan is visible or not. I'll try a bit more, but I'm starting to run out of ideas.

**Comment by devinroth** [comment]
You need to notify HAL of the change.

Devin

**Comment by devinroth** [comment]
Let me give it a try.

**Comment by HEnquist** [comment]
Ok, IIUC I need to notify the host via RequestDeviceConfigurationChange: https://github.com/phracker/MacOSX-SDKs/blob/master/MacOSX10.9.sdk/System/Library/Frameworks/CoreAudio.framework/Versions/A/Headers/AudioServerPlugIn.h#L529
I'll give it a go.

**Comment by devinroth** [comment]
Take a look at what happens the aquire audio box changes. Try something similar.

Devin

**Comment by devinroth** [comment]
Hopefully that makes sense.

**Comment by HEnquist** [comment]
Yes this is very helpful, I'm making progress! I managed to get it to dynamically add/remove the pan control, but at the moment it's only vaguely connected to what I do with the clock source control :)
It feels like I'm getting close!

**Comment by HEnquist** [comment]
Got it! Now I can start cleaning up the ugly hacks I made trying to get this to work...

**Comment by devinroth** [comment]
I’m a 4 spaces kind of guy.

device2 is a mirrored device that is hidden by default. If you unhide it (see macros at top) it creates another audio device that is exact the same in every way shape and form. What this allows is to separate the input and output to different devices. So you could have one device with just the input and the other with just the output.

When I’m working on projects I usually hide one  so a user is only presented with an input or an output to make it more fool proof.

Hope that makes sense.

Devin

**Comment by devinroth** [comment]
Not updating for me.

**Comment by devinroth** [comment]
I'll take a closer look tomorrow.

**Comment by HEnquist** [comment]
Hmm strange, it works fine on my new M1 Air with Ventura. I'll also try in on my old MBP and report how that went.

**Comment by devinroth** [comment]
I was on M1 Ventura.

Could you double check to make sure you pushed your latest changes?

I’m done that many times.

Devin

**Comment by HEnquist** [comment]
Just checked, and yes my branch "clocksource_select" has the latest version.
I'm testing it with Audio MIDI Setup. Switching between Internal Fixed and Internal Adjustable makes the pan control appear or disappear as it should.

**Comment by devinroth** [comment]
Maybe I didn’t pull the latest. At least I thought I pulled the latest.

Devin

**Comment by HEnquist** [comment]
Great that it works! Adding this feature of removing the pan control when it's disabled was a brilliant idea, it really reduces the risk of confusion. The pitch adjust should of course also be mentioned in the documentation. Where should that go?

**Comment by Wang-Yue** [comment]
By reading the pointers in README, it seems that the most appropriate place to include this doc is the wiki (https://github.com/ExistentialAudio/BlackHole/wiki).

**Comment by HEnquist** [comment]
Yes the wiki seems to be the best place to document this. I'm not familiar with how it works, but I think it's not possible to submit a pull request for it. Would it work if I do the changes and just post the diff here?

**Comment by devinroth** [comment]
Sure.

Devin

**Comment by devinroth** [comment]
So there was a couple issues with device2. One which I can fix and the other I think is a problem that was always there. I'll push a change soon.

**Comment by HEnquist** [comment]
Here is a draft of the wiki changes. Feedback is appreciated :)
[rateadjust.patch](https://github.com/ExistentialAudio/BlackHole/files/10540484/rateadjust.patch)

**Review by devinroth — APPROVED** [review]

**Comment by devinroth** [comment]
I'm just going to merge. I'll fix the device2 issue separately.

**Comment by devinroth** [comment]
We can continue wiki discussion on a discussions thread.

**Comment by HEnquist** [comment]
Thanks! I'll open a discussion thread on the wiki changes soon (when I'm not using a phone..)

**Comment by devinroth** [comment]
Perfect. I added the page to the wiki already. We can discuss any changes once I’ve given it more thought.

Or, if you’re on discord, I recently started one up for BlackHole. We can move the discussion over there if you prefer.

Devin

**Pull request merged**
