### PR TITLE
Control for pitch adjust

### PR DESCRIPTION
**Pull request by HEnquist**
This is a prototype that exposes a control for adjusting the sample rate of the Blackhole device by +- 1%. This functionality is provided by the standard Alsa loopback device on Linux, and is very useful for syncing the loopback to other things, that may or may not be another Alsa device.

For now it uses the balance control of the playback side for the control. The balance control is perhaps not the ideal choice., but I have not yet figured out how to (and if it's possible) to add a custom control. 

Would you be willing to include something like this in Blackhole?

### CODE REVIEW

**Comment by devinroth** [comment]
Sorry I can’t even look at anything without the CLA signed. I License BlackHole to 3rd parties and I want to avoid any copyright infringement.

Devin

**Comment by HEnquist** [comment]
Alright, understood. I just find these legal things so tedious, but I have read and signed it now.

**Comment by devinroth** [comment]
This is interesting. Yes a custom control would be a better solution. I'm curious on how this would be implemented. Would you just monitor the clocks of BlackHole and another device and adjust BlackHole when it starts to drift? 

My solution, was to synchronize BlackHole clock with that of a different audio device. That's still in development but there were a couple hiccups that need to be ironed out.

**Comment by HEnquist** [comment]
I basically record from one device, do some processing on the audio data, push it to a buffer, and play it back on another device from that buffer. At the same time I monitor how many frames I have in the buffer. If it's lower or higher that the target value, I adjust the speed of the capture device to keep the level constant. When the capture device is an Alsa loopback (on Linux), I adjust the virtual clock of that device. When it's anything else, I instead insert an asynchronous resampler that I adjust. If Blackhole is also adjustable, then I can get rid of this resampler on MacOs too.

I'll continue and try to figure out how to add custom controls the. I think this adjust feature would coexist nicely with your other option of locking the clock to another device.

**Comment by HEnquist** [comment]
BTW I'm struggling with finding relevant coreaudio documentation. Does anyone have any advice on where to find something? A book perhaps?

**Comment by devinroth** [comment]
I was thinking AudioSliderControl but just reading the docs it looks like it only uses UInt32. You probably want to use a float.

So maybe your idea of using the AudioStereoControlPan is the best. Doesn’t look like there’s much customizability with these built-in controls unfortunately.

Devin

**Comment by HEnquist** [comment]
Uint32 should be just fine! I think an allowed range of +-1% is reasonable. Dividing that up into 2^32 steps already gives more precision than needed. 
I think I have figured out how to add custom controls. Will try it as soon as I have a little time.

**Comment by HEnquist** [comment]
It seems like custom controls are not shown in Audio Midi Setup. I think the rate control should be accessible from there, if not it needs some app to expose it to the user. 
I have only managed to get it to show the stereo pan control. This works but it might be a bit confusing that the pitch is called "Balance". I have tried changing that label but without success. I just want a slider called pitch, do you have any ideas for how to achieve that?

**Comment by HEnquist** [comment]
I'm guessing that Audio Midi Setup only checks for (and shows) a few different standard controls. It doesn't seem to be possible to customize those with names etc (or at least I haven't managed).
What do you prefer, using an existing control like "Balance" and living with the risk of confusion, or adding a custom control and bundling Blackhole with a small app (tiny GUI or cli tool) to access the control?

**Comment by HEnquist** [comment]
Just had a (maybe) good idea. What if we add a ClockSource control, with two values called something like "InternalFixed" and "InternalAdjustable"? Default is "InternalFixed" where everything is the same as before, and "InternalAdjustable" enables adjusting via the pan control. And later the list can be extended with the other devices for syncing the clock to another device.

**Comment by devinroth** [comment]
THere’s actually a clock source control that I was going to use for external syncing.

Devin

**Comment by Wang-Yue** [comment]
will there still be an update on this feature?

**Comment by HEnquist** [comment]
Rebased on current master. I had to change the os target version back to 11.1 since my old Mac can't run the latest Xcode. This is a bit annoying since it meant I had to rename `kAudioObjectPropertyElementMain` back to the old `kAudioObjectPropertyElementMaster` to be able to compile. Is it ok if I leave it like this in the PR?

I haven't looked at the clock source selection yet. Should I continue using the balance control for the rate, and add the clock source selection as I suggested before? Just want to confirm this before I start any work.

**Comment by devinroth** [comment]
Why not do something like define kAudioObjectPropertyElementMain = kAudioObjectPropertyElementMaster if target is below a certain macOS version? Then it works in all instances.

**Comment by HEnquist** [comment]
> Why not do something like define kAudioObjectPropertyElementMain = kAudioObjectPropertyElementMaster if target is below a certain macOS version? Then it works in all instances.

Good idea, done!

I'm still wondering about the clock source select and use of the pan control, can you please share your view on that?

**Comment by HEnquist** [comment]
The changes for adding a clock source selection are here:
https://github.com/HEnquist/BlackHole/pull/1
This adds the sources "Internal Fixed" and "Internal Adjustable", where the adjustable one activates the adjust via the pan control.

**Comment by Wang-Yue** [comment]
Hi, Devin any chance to prioritize the review and merge these changes in? Thanks!

**Comment by HEnquist** [comment]
> I'm still wondering about the clock source select and use of the pan control, can you please share your view on that?

I'm still not sure what to do here. Should I merge the clock source select to this pr or not?

**Comment by devinroth** [comment]
Nah. I can deal with that another time.

But please merge master into your branch.

Devin

**Comment by HEnquist** [comment]
I did that a couple of weeks ago, I don't see any changes in master since then.

Then I leave this PR as is, and submit another one for the clock source select.

**Comment by HEnquist** [comment]
Should I get rid of the changes in the other files than Blackhole.c?

**Comment by devinroth** [comment]
Yeah.

Devin

**Comment by Wang-Yue** [comment]
Any chance this could be merged soon?

**Comment by devinroth** [comment]
I'll be able to look at this over the next week.

**Comment by devinroth** [comment]
Looking at this now!

**Review by devinroth — APPROVED** [review]
Looks good. Thanks for all the hard work on this. I hope it help some people out.

**Comment by HEnquist** [comment]
Sweet thanks!! Then I will follow up with another pr very soon, for adding a clock source selector.

**Comment by devinroth** [comment]
I should mention I noticed some audio glitches when changing the value. I’ll look into the more.

Devin

**Comment by HEnquist** [comment]
Oh I'll look into that too then! I haven't noticed any glitches, but I usually change the value very little. How big of a change did you make?

**Comment by Wang-Yue** [comment]
Good news that this is finally merged in!

**Pull request merged**
