### PR TITLE
use travis for builds

### PR DESCRIPTION
**Pull request by stephengroat**
https://travis-ci.com/stephengroat/BlackHole/jobs/251613108

### CODE REVIEW

**Comment by stephengroat** [comment]
Let me know if you need help turning travis on for the org/repo

**Comment by devinroth** [comment]
Sure that would be helpful. I’ve done it one in the past but it’s not like I remember.

**Comment by stephengroat** [comment]
You really should on need #1-3 of this link: https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci

**Comment by devinroth** [comment]
Thanks

**Pull request merged**
