### PR TITLE
Fix typos in comments

### PR DESCRIPTION
**Pull request by leafac**
Thank you very much for BlackHole!

I use BlackHole extensively (4 instances 😃) to make my streams and video calls work the way I want.

Now I’m going over the source and it’s a great read! Very educational!

You’re awesome!

### CODE REVIEW

**Comment by leafac** [comment]
By the way, another thing I found (but apparently I can’t send a pull request for the wiki):

On this page https://github.com/ExistentialAudio/BlackHole/wiki/Running-Multiple-BlackHole-Drivers the line `sudo killall coreaudiod` should be replaced with `sudo launchctl kickstart -kp system/com.apple.audio.coreaudiod` (which I found on the README and at https://github.com/ExistentialAudio/BlackHole/wiki/Build-with-Xcode). With the first command it seems like coreaudiod sometimes doesn’t restart when you kill it, and you end up with no audio devices. The second commend worked every time for me.

**Comment by devinroth** [comment]
Thanks. Sorry this took so long to Merge.

**Comment by leafac** [comment]
@devinroth Don’t worry about it. And thanks for creating BlackHole. I use four instances of it every day!

After sending the pull request I realized that this part of the codebase actually comes from https://developer.apple.com/documentation/coreaudio/creating_an_audio_server_driver_plug-in so it’s kind of silly to fix that typo 🤷

**Comment by devinroth** [comment]
Lol.

It’s a typo non the less.

Devin

**Pull request merged**
